<a href="https://colab.research.google.com/github/anirbanghoshsbi/.github.io/blob/master/work/err/cross_section_momentum/temp_work_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#----------Read ZIP Files Extract the CSV files and put them in a folder levelone---------
import os
import zipfile
import shutil
import pandas as pd
import numpy as np

source_folder = "/content"           # Folder containing ZIP files
levelone_folder = "/content/levelone"

os.makedirs(levelone_folder, exist_ok=True)

def extract_all_zips(source, destination):

    # First copy all zip files to levelone
    for file in os.listdir(source):
        if file.endswith(".zip"):
            shutil.copy(os.path.join(source, file), destination)

    # Now recursively extract inside levelone
    while True:
        zip_found = False

        for root, dirs, files in os.walk(destination):
            for file in files:
                if file.endswith(".zip"):
                    zip_found = True
                    zip_path = os.path.join(root, file)

                    with zipfile.ZipFile(zip_path, 'r') as z:
                        z.extractall(root)

                    os.remove(zip_path)
                    print(f"Extracted and removed: {file}")

        if not zip_found:
            break

    print("All ZIP files fully extracted into levelone.")


extract_all_zips(source_folder, levelone_folder)

Extracted and removed: levelone_archive.zip
All ZIP files fully extracted into levelone.

In [ ]:
#-----Connect my Coding Terminal to Google Drive------
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.tail(5)

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
3610523,ZOTA,EQ,1208.50,1220.00,1177.15,1201.50,1200.65,1195.10,61764,7.424303e+07,2025-07-25,7246,INE358U01012
3610524,ZUARI,EQ,217.56,217.56,212.10,213.57,213.50,218.14,109229,2.336998e+07,2025-07-25,2381,INE840M01016
3610525,ZUARIIND,EQ,268.90,272.00,264.15,265.10,265.20,270.00,32471,8.655200e+06,2025-07-25,1135,INE217A01012
3610526,ZYDUSLIFE,EQ,967.20,981.95,960.50,976.40,973.50,971.25,1188906,1.159735e+09,2025-07-25,39311,INE010B01027
3610527,ZYDUSWELL,EQ,2149.40,2157.40,2092.90,2102.60,2093.40,2138.10,44772,9.463579e+07,2025-07-25,8027,INE768C01010

In [ ]:
# We are appending all the csv files into a single pandas dataframe
import pandas as pd
import glob
import os

# Path to folder containing CSV files
folder_path = "/content/levelone"

# Get all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Read and append
df_list = []

for file in csv_files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

# Combine all into one dataframe
full_data_from_csv = pd.concat(df_list, ignore_index=True)

In [ ]:
full_data_from_csv.columns

Index(['TradDt', 'BizDt', 'Sgmt', 'Src', 'FinInstrmTp', 'FinInstrmId', 'ISIN',
       'TckrSymb', 'SctySrs', 'XpryDt', 'FininstrmActlXpryDt', 'StrkPric',
       'OptnTp', 'FinInstrmNm', 'OpnPric', 'HghPric', 'LwPric', 'ClsPric',
       'LastPric', 'PrvsClsgPric', 'UndrlygPric', 'SttlmPric', 'OpnIntrst',
       'ChngInOpnIntrst', 'TtlTradgVol', 'TtlTrfVal', 'TtlNbOfTxsExctd',
       'SsnId', 'NewBrdLotQty', 'Rmks', 'Rsvd1', 'Rsvd2', 'Rsvd3', 'Rsvd4'],
      dtype='object')

In [ ]:
df.columns

Index(['SYMBOL', 'SERIES', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'LAST', 'PREVCLOSE',
       'TOTTRDQTY', 'TOTTRDVAL', 'TIMESTAMP', 'TOTALTRADES', 'ISIN'],
      dtype='object')

In [ ]:
# Remove unwanted columns
#df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
#------#----------------#----------------#---------#

#We Do a Column Mapping So that the Pandas Dataframe and the Duckdb Dataframe has the same Column Names
# Column mapping
column_mapping = {
    "TckrSymb": "SYMBOL",
    "SctySrs": "SERIES",
    "OpnPric": "OPEN",
    "HghPric": "HIGH",
    "LwPric": "LOW",
    "ClsPric": "CLOSE",
    "LastPric": "LAST",
    "PrvsClsgPric": "PREVCLOSE",
    "TtlTradgVol": "TOTTRDQTY",
    "TtlTrfVal": "TOTTRDVAL",
    "BizDt": "TIMESTAMP",
    "TtlNbOfTxsExctd": "TOTALTRADES",
    "ISIN": "ISIN"
}

# Subset + rename
subset_full_data = full_data_from_csv[list(column_mapping.keys())].copy()
subset_full_data.rename(columns=column_mapping, inplace=True)

In [ ]:
subset_full_data

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
0,SGBJUN28,GB,14000.0,14130.30,13920.00,14080.00,14080.00,14295.48,446,6.262022e+06,2026-04-02,103,IN0020200104
1,SGBN28VIII,GB,14286.0,14286.00,13950.01,14138.00,14138.00,14285.11,126,1.778378e+06,2026-04-02,48,IN0020200286
2,SGBMAY29I,GB,14150.0,14399.99,14010.00,14279.76,14341.00,14304.99,571,8.053976e+06,2026-04-02,86,IN0020210053
3,SGBJUN29II,GB,14071.0,14101.00,13950.00,14052.22,14052.22,14295.00,127,1.783057e+06,2026-04-02,23,IN0020210061
4,SGBJU29III,GB,14300.0,14300.00,13875.01,14057.98,14060.00,14300.00,363,5.111206e+06,2026-04-02,56,IN0020210087
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6634,ZOTA,EQ,1114.8,1136.00,1099.20,1116.20,1120.00,1064.80,35344,3.960813e+07,2026-04-01,1966,INE358U01012
6635,ZUARI,EQ,187.0,197.93,185.69,196.37,197.92,181.17,254485,4.924645e+07,2026-04-01,3847,INE840M01016
6636,ZUARIIND,EQ,217.0,232.39,217.00,229.81,230.00,213.30,50867,1.159656e+07,2026-04-01,1546,INE217A01012
6637,ZYDUSLIFE,EQ,888.0,900.00,857.10,863.20,866.00,871.20,768431,6.710694e+08,2026-04-01,37264,INE010B01027
6638,ZYDUSWELL,EQ,445.0,445.00,431.10,435.75,431.10,426.35,194848,8.510888e+07,2026-04-01,9491,INE768C01028

In [ ]:
df.tail(2)

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
3610526,ZYDUSLIFE,EQ,967.2,981.95,960.5,976.4,973.5,971.25,1188906,1.159735e+09,2025-07-25,39311,INE010B01027
3610527,ZYDUSWELL,EQ,2149.4,2157.40,2092.9,2102.6,2093.4,2138.10,44772,9.463579e+07,2025-07-25,8027,INE768C01010

In [ ]:
df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"])
subset_full_data["TIMESTAMP"] = pd.to_datetime(subset_full_data["TIMESTAMP"])

In [ ]:
# stack rows
combined = pd.concat([df, subset_full_data], ignore_index=True)

# sort chronologically
combined = combined.sort_values(["SYMBOL", "TIMESTAMP"])

# reset index
combined = combined.reset_index(drop=True)

In [ ]:
#Check consistttency
print("Rows in df1:", len(df))
print("Rows in df2:", len(subset_full_data))
print("Rows in combined:", len(combined))

Rows in df1: 3610528
Rows in df2: 144079
Rows in combined: 3754607

In [ ]:
print(combined["TIMESTAMP"].max())
print(combined["TIMESTAMP"].min())

2026-03-06 00:00:00
2020-01-01 00:00:00

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Database updated successfully.

In [ ]:
#combined.to_parquet("/content/drive/MyDrive/equities_combined.parquet", index=False)