<a href="https://colab.research.google.com/github/anirbanghoshsbi/.github.io/blob/master/work/err/cross_section_momentum/temp_work_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#----------Read ZIP Files Extract the CSV files and put them in a folder levelone---------
import os
import zipfile
import shutil
import pandas as pd
import numpy as np

source_folder = "/content"           # Folder containing ZIP files
levelone_folder = "/content/levelone"

os.makedirs(levelone_folder, exist_ok=True)

def extract_all_zips(source, destination):

    # First copy all zip files to levelone
    for file in os.listdir(source):
        if file.endswith(".zip"):
            shutil.copy(os.path.join(source, file), destination)

    # Now recursively extract inside levelone
    while True:
        zip_found = False

        for root, dirs, files in os.walk(destination):
            for file in files:
                if file.endswith(".zip"):
                    zip_found = True
                    zip_path = os.path.join(root, file)

                    with zipfile.ZipFile(zip_path, 'r') as z:
                        z.extractall(root)

                    os.remove(zip_path)
                    print(f"Extracted and removed: {file}")

        if not zip_found:
            break

    print("All ZIP files fully extracted into levelone.")


extract_all_zips(source_folder, levelone_folder)

Extracted and removed: Reports-Archives-Multiple-27012026.zip
Extracted and removed: Reports-Archives-Multiple-23012026.zip
Extracted and removed: Reports-Archives-Multiple-02032026.zip
Extracted and removed: Reports-Archives-Multiple-20022026.zip
Extracted and removed: Reports-Archives-Multiple-05032026.zip
Extracted and removed: Reports-Archives-Multiple-12012026.zip
Extracted and removed: Reports-Archives-Multiple-09022026.zip
Extracted and removed: Reports-Archives-Multiple-19022026.zip
Extracted and removed: Reports-Archives-Multiple-30012026.zip
Extracted and removed: Reports-Archives-Multiple-19012026.zip
Extracted and removed: Reports-Archives-Multiple-25022026.zip
Extracted and removed: Reports-Archives-Multiple-11022026.zip
Extracted and removed: Reports-Archives-Multiple-23022026.zip
Extracted and removed: Reports-Archives-Multiple-04032026.zip
Extracted and removed: Reports-Archives-Multiple-06022026.zip
Extracted and removed: Reports-Archives-Multiple-06012026.zip
Extracted and removed: Reports-Archives-Multiple-13022026.zip
Extracted and removed: Reports-Archives-Multiple-12022026.zip
Extracted and removed: Reports-Archives-Multiple-28012026.zip
Extracted and removed: Reports-Archives-Multiple-27022026.zip
Extracted and removed: Reports-Archives-Multiple-09012026.zip
Extracted and removed: Reports-Archives-Multiple-18022026.zip
Extracted and removed: Reports-Archives-Multiple-06032026.zip
Extracted and removed: Reports-Archives-Multiple-08012026.zip
Extracted and removed: Reports-Archives-Multiple-05012026.zip
Extracted and removed: Reports-Archives-Multiple-24022026.zip
Extracted and removed: Reports-Archives-Multiple-21012026.zip
Extracted and removed: Reports-Archives-Multiple-03022026.zip
Extracted and removed: Reports-Archives-Multiple-05022026.zip
Extracted and removed: Reports-Archives-Multiple-22012026.zip
Extracted and removed: Reports-Archives-Multiple-02022026.zip
Extracted and removed: Reports-Archives-Multiple-01012026.zip
Extracted and removed: Reports-Archives-Multiple-16012026.zip
Extracted and removed: Reports-Archives-Multiple-16022026.zip
Extracted and removed: Reports-Archives-Multiple-13012026.zip
Extracted and removed: Reports-Archives-Multiple-10022026.zip
Extracted and removed: Reports-Archives-Multiple-07012026.zip
Extracted and removed: Reports-Archives-Multiple-17022026.zip
Extracted and removed: Reports-Archives-Multiple-14012026.zip
Extracted and removed: Reports-Archives-Multiple-29012026.zip
Extracted and removed: Reports-Archives-Multiple-26022026.zip
Extracted and removed: Reports-Archives-Multiple-04022026.zip
Extracted and removed: Reports-Archives-Multiple-20012026.zip
Extracted and removed: Reports-Archives-Multiple-02012026.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260206_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260121_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260113_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260305_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260218_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260219_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260101_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260105_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260127_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260203_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260123_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260106_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260128_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260109_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260211_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260213_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260304_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260119_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260220_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260202_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260227_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260107_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260205_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260306_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260108_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260223_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260225_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260224_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260209_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260210_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260212_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260116_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260112_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260122_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260129_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260114_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260130_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260302_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260204_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260226_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260217_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260216_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260120_F_0000.csv.zip
Extracted and removed: BhavCopy_NSE_CM_0_0_0_20260102_F_0000.csv.zip
All ZIP files fully extracted into levelone.

In [ ]:
#-----Connect my Coding Terminal to Google Drive------
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
#Import Database using duckdb
import duckdb

with duckdb.connect("/content/All_equities_2020_onwards.duckdb") as con:
    df = con.execute("SELECT * FROM equities").fetchdf()

print(df.shape)

(3610528, 13)

In [2]:
df.columns

Index(['SYMBOL', 'SERIES', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'LAST', 'PREVCLOSE',
       'TOTTRDQTY', 'TOTTRDVAL', 'TIMESTAMP', 'TOTALTRADES', 'ISIN'],
      dtype='object')

In [3]:
df.tail(5)

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
3610523,ZOTA,EQ,1208.50,1220.00,1177.15,1201.50,1200.65,1195.10,61764,7.424303e+07,2025-07-25,7246,INE358U01012
3610524,ZUARI,EQ,217.56,217.56,212.10,213.57,213.50,218.14,109229,2.336998e+07,2025-07-25,2381,INE840M01016
3610525,ZUARIIND,EQ,268.90,272.00,264.15,265.10,265.20,270.00,32471,8.655200e+06,2025-07-25,1135,INE217A01012
3610526,ZYDUSLIFE,EQ,967.20,981.95,960.50,976.40,973.50,971.25,1188906,1.159735e+09,2025-07-25,39311,INE010B01027
3610527,ZYDUSWELL,EQ,2149.40,2157.40,2092.90,2102.60,2093.40,2138.10,44772,9.463579e+07,2025-07-25,8027,INE768C01010

In [6]:
# We are appending all the csv files into a single pandas dataframe
import pandas as pd
import glob
import os

# Path to folder containing CSV files
folder_path = "/content/levelone"

# Get all CSV files
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Read and append
df_list = []

for file in csv_files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

# Combine all into one dataframe
full_data_from_csv = pd.concat(df_list, ignore_index=True)

In [7]:
full_data_from_csv.columns

Index(['TradDt', 'BizDt', 'Sgmt', 'Src', 'FinInstrmTp', 'FinInstrmId', 'ISIN',
       'TckrSymb', 'SctySrs', 'XpryDt', 'FininstrmActlXpryDt', 'StrkPric',
       'OptnTp', 'FinInstrmNm', 'OpnPric', 'HghPric', 'LwPric', 'ClsPric',
       'LastPric', 'PrvsClsgPric', 'UndrlygPric', 'SttlmPric', 'OpnIntrst',
       'ChngInOpnIntrst', 'TtlTradgVol', 'TtlTrfVal', 'TtlNbOfTxsExctd',
       'SsnId', 'NewBrdLotQty', 'Rmks', 'Rsvd1', 'Rsvd2', 'Rsvd3', 'Rsvd4'],
      dtype='object')

In [ ]:
df.columns

Index(['SYMBOL', 'SERIES', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'LAST', 'PREVCLOSE',
       'TOTTRDQTY', 'TOTTRDVAL', 'TIMESTAMP', 'TOTALTRADES', 'ISIN'],
      dtype='object')

In [8]:
# Remove unwanted columns
#df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
#------#----------------#----------------#---------#

#We Do a Column Mapping So that the Pandas Dataframe and the Duckdb Dataframe has the same Column Names
# Column mapping
column_mapping = {
    "TckrSymb": "SYMBOL",
    "SctySrs": "SERIES",
    "OpnPric": "OPEN",
    "HghPric": "HIGH",
    "LwPric": "LOW",
    "ClsPric": "CLOSE",
    "LastPric": "LAST",
    "PrvsClsgPric": "PREVCLOSE",
    "TtlTradgVol": "TOTTRDQTY",
    "TtlTrfVal": "TOTTRDVAL",
    "BizDt": "TIMESTAMP",
    "TtlNbOfTxsExctd": "TOTALTRADES",
    "ISIN": "ISIN"
}

# Subset + rename
subset_full_data = full_data_from_csv[list(column_mapping.keys())].copy()
subset_full_data.rename(columns=column_mapping, inplace=True)

In [9]:
subset_full_data.tail(2)

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
144077,ZYDUSLIFE,EQ,894.0,903.9,889.0,896.9,896.8,906.90,1277388,1.143827e+09,2026-03-04,45067,INE010B01027
144078,ZYDUSWELL,EQ,378.4,382.5,371.3,377.1,376.8,378.95,131836,4.984932e+07,2026-03-04,11195,INE768C01028

In [10]:
df.tail(2)

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
3610526,ZYDUSLIFE,EQ,967.2,981.95,960.5,976.4,973.5,971.25,1188906,1.159735e+09,2025-07-25,39311,INE010B01027
3610527,ZYDUSWELL,EQ,2149.4,2157.40,2092.9,2102.6,2093.4,2138.10,44772,9.463579e+07,2025-07-25,8027,INE768C01010

In [12]:
df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"])
subset_full_data["TIMESTAMP"] = pd.to_datetime(subset_full_data["TIMESTAMP"])

In [13]:
# stack rows
combined = pd.concat([df, subset_full_data], ignore_index=True)

# sort chronologically
combined = combined.sort_values(["SYMBOL", "TIMESTAMP"])

# reset index
combined = combined.reset_index(drop=True)

In [14]:
#Check consistttency
print("Rows in df1:", len(df))
print("Rows in df2:", len(subset_full_data))
print("Rows in combined:", len(combined))

Rows in df1: 3610528
Rows in df2: 144079
Rows in combined: 3754607

In [15]:
print(combined["TIMESTAMP"].max())
print(combined["TIMESTAMP"].min())

2026-03-06 00:00:00
2020-01-01 00:00:00

In [16]:
import duckdb

db_path = "/content/All_equities_2020_onwards.duckdb"

with duckdb.connect(db_path) as con:

    # Register dataframe so DuckDB can read it
    con.register("combined_df", combined)

    # Replace table with updated dataframe
    con.execute("""
        CREATE OR REPLACE TABLE equities AS
        SELECT * FROM combined_df
    """)

print("Database updated successfully.")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Database updated successfully.

In [17]:
combined.to_parquet("/content/drive/MyDrive/equities_combined.parquet", index=False)